spring.application.name=Titan
server.port=2002

#spring.datasource.url=jdbc:postgresql://ep-misty-flower-a8djo7lt-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_tzFEWJQVe30i

spring.datasource.url=jdbc:jdbc:postgresql://localhost:2002/titan
spring.datasource.username=postgres
spring.datasource.password=postroot

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
