name: Keep Render Backend Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to keep Render alive
        run: curl -m 10 https://titan-api-ffre.onrender.com || echo "Server might be down"
